# Generated by Django 2.0.7 on 2018-07-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180714_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='category',
            new_name='smallcategory',
        ),
        migrations.AlterField(
            model_name='category',
            name='guonei',
            field=models.BooleanField(default=1, verbose_name='国内'),
        ),
    ]
