# Generated by Django 2.0.6 on 2018-07-17 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180716_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': '大分类', 'verbose_name_plural': '大分类'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['id'], 'verbose_name': '站点', 'verbose_name_plural': '站点'},
        ),
        migrations.AlterModelOptions(
            name='smallcategory',
            options={'ordering': ['id'], 'verbose_name': '小分类', 'verbose_name_plural': '小分类'},
        ),
    ]
