# Generated by Django 2.0.6 on 2018-07-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180717_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='backgroundcategory',
            name='desc',
        ),
    ]
