# Generated by Django 2.0.6 on 2018-07-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180717_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='preview_url',
            field=models.ImageField(default='images/BackGround/preview/background.png', upload_to='images/BackGround/preview/%Y/%m/%d', verbose_name='预览图'),
        ),
        migrations.AlterField(
            model_name='background',
            name='image_url',
            field=models.ImageField(upload_to='images/BackGround/image/%Y/%m/%d', verbose_name='真实图片'),
        ),
    ]
