# Generated by Django 2.1.2 on 2018-10-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20180717_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'id'], 'verbose_name': '大分类', 'verbose_name_plural': '大分类'},
        ),
        migrations.AlterModelOptions(
            name='smallcategory',
            options={'ordering': ['order', 'id'], 'verbose_name': '小分类', 'verbose_name_plural': '小分类'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['order', 'id'], 'verbose_name': '站点', 'verbose_name_plural': '站点'},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=1, help_text='分类显示顺序', verbose_name='顺序'),
        ),
        migrations.AddField(
            model_name='smallcategory',
            name='order',
            field=models.IntegerField(default=1, help_text='分类显示顺序', verbose_name='顺序'),
        ),
        migrations.AddField(
            model_name='site',
            name='order',
            field=models.IntegerField(default=1, help_text='站点显示顺序', verbose_name='顺序'),
        ),
    ]
