# Generated by Django 2.1.2 on 2018-10-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20181019_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='image_url',
            field=models.ImageField(default='images/Site/default.png', upload_to='images/Site/%Y/%m/%d', verbose_name='图片'),
        ),
    ]
